version: '3'

services:
  surrealdb:
    env_file:
      - .env
    entrypoint: 
      - /surreal 
      - start 
      - --user=root
      - --pass=root
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000